# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
