# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('eur', 'EUR'), ('usd', 'USD'), ('uah', 'UAH')], default='eur', max_length=3)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('currency', models.CharField(choices=[('eur', 'EUR'), ('usd', 'USD'), ('uah', 'UAH')], default='eur', max_length=3)),
                ('transaction_date', models.DateTimeField()),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ServiceProvider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('currency', models.CharField(choices=[('eur', 'EUR'), ('usd', 'USD'), ('uah', 'UAH')], default='eur', max_length=3)),
                ('transaction_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
