# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='total_revenue',
        ),
    ]
