# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_balance_total_revenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='user',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='balance',
            name='currency',
            field=models.CharField(choices=[('eur', '€'), ('usd', '$'), ('uah', '₴')], default='eur', max_length=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(choices=[('eur', '€'), ('usd', '$'), ('uah', '₴')], default='eur', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('eur', '€'), ('usd', '$'), ('uah', '₴')], default='eur', max_length=3),
        ),
    ]
