# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitedmember',
            name='author',
        ),
        migrations.RemoveField(
            model_name='invitedmember',
            name='invitee',
        ),
        migrations.RemoveField(
            model_name='invitedmember',
            name='service_provider',
        ),
        migrations.DeleteModel(
            name='InvitedMember',
        ),
    ]
